# Site settings
#email: 
title: "reo homepage"
description: "LeoP homepage"
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#github_username: reo

plugins:
  - kramdown
#, github-pages]

# if pagination is desired, set up the following instead:
# plugins: [jekyll-paginate, kramdown]
# paginate: 5
# paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
